Tensor Arrays: Similar to NumPy ndarrays

In [1]:
import torch


In [3]:
x = torch.empty(5,3)


In [4]:
from __future__ import print_function


In [5]:
print(x)

tensor([[-2.4047e-33, -1.1558e+23,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-7.3244e+10,  2.5168e+29,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.2275e+32, -1.5592e-01,  0.0000e+00]])


In [6]:
x = torch.rand(5, 3)

In [7]:
print(x)

tensor([[0.2884, 0.0085, 0.1222],
        [0.7608, 0.4588, 0.4392],
        [0.1035, 0.8666, 0.8725],
        [0.8672, 0.3373, 0.5770],
        [0.7947, 0.3659, 0.3947]])


In [8]:
x=torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
x = torch.tensor([
    [3, 5],
    [4, 2.5]
]
)
print(x)

tensor([[3.0000, 5.0000],
        [4.0000, 2.5000]])


In [11]:
y = torch.tensor([
    [-2, -5],
    [4, 0.5]
])
print(x + y)

tensor([[1., 0.],
        [8., 3.]])


In [12]:
print(torch.add(x, y))

tensor([[1., 0.],
        [8., 3.]])


In [13]:
torch.cuda.get_device_name()


'Tesla K80'